# Generated by Django 3.1.5 on 2021-01-22 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weather.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Use the capitalize format, e.g: Madrid', max_length=50)),
                ('country', models.CharField(help_text='Use the capitalize format, e.g: Spain', max_length=50)),
                ('temperature', models.IntegerField(help_text='Temperature in ºC', validators=[weather.models.validate_temperature])),
                ('atmospheric_pressure', models.FloatField(help_text='Atmospheric pressure in mbar')),
                ('wind_sped', models.PositiveIntegerField(help_text='Wind speed in km/h')),
                ('wind_direction', models.CharField(choices=[('undefined', 'Undefined'), ('n', 'N'), ('ne', 'NE'), ('e', 'E'), ('se', 'SE'), ('s', 'S'), ('sw', 'SW'), ('w', 'W'), ('nw', 'NW')], default='undefined', max_length=9, verbose_name='Wind direction')),
                ('humidity', models.PositiveIntegerField(validators=[weather.models.validate_humidity_precipitation])),
                ('precipitation_probability', models.PositiveIntegerField(validators=[weather.models.validate_humidity_precipitation])),
                ('types_precipitation', models.CharField(choices=[('undefined', 'Undefined'), ('rain', 'Rain'), ('drizzle', 'Drizzle'), ('snow', 'Snow'), ('hail', 'Hail')], default='undefined', max_length=9, verbose_name='Types of Precipitation')),
                ('cloudiness', models.CharField(choices=[('undefined', 'Undefined'), ('clear', 'Clear'), ('mostly_clear', 'Mostly Clear'), ('partly_cloudy', 'Partly Cloudy'), ('mostly_cloudy', 'Mostly Cloudy'), ('cloudy', 'Cloudy')], default='undefined', max_length=13, verbose_name='Cloudiness')),
                ('visibility', models.FloatField(help_text='Visibility in km', validators=[weather.models.validate_visibility])),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
